apiVersion: v1
kind: Template
metadata:
  name: java-template
objects:
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}
    annotations:
      haproxy.router.openshift.io/balance: roundrobin
  spec:
    tls:
      termination: reencrypt
    to:
      kind: Service
      name: ${MAJOR_SERVICE_NAME}
      weight: 75
    alternateBackends:
    - kind: Service
      name: ${MINOR_SERVICE_NAME}
      weight: 25
parameters:
- name: APPLICATION_NAME
  description: The name for the application.
  displayName: Application name
  value: ssl-server
  required: true
- name: MAJOR_SERVICE_NAME
  description: Service to connect to
  displayName: Service name
  required: true
- name: MINOR_SERVICE_NAME
  description: Service to connect to
  displayName: Service name
  required: true
